export const JLCEDA_STYLE = {
  colors: {
    background: '#FFFFFF',
    grid: '#E8EEF4',
    gridMajor: '#C8D4E0',
    border: '#A0A8B4',
    titleBlock: {
      border: '#C00000',
      text: '#000000',
      background: '#FFFEF5',
      highlight: '#FFF0F0',
      company: '#000080',
    },
    components: {
      outline: '#000000',
      fill: '#FFFFFF',
      fillAlt: '#F8F8F8',
      pin: '#000000',
      pinName: '#0000A0',
      pinNumber: '#606060',
      refDes: '#000000',
      value: '#008000',
      partNumber: '#0000FF',
    },
    wires: {
      signal: '#000000',
      power: '#000000',
      ground: '#000000',
      bus: '#000000',
      highlight: '#FF0000',
      noconnect: '#808080',
    },
    netLabels: {
      default: '#000000',
      power: '#000000',
      ground: '#000000',
      input: '#000000',
      output: '#000000',
    },
    regions: {
      power: '#E8F4FC',
      mcu: '#F0F8E8',
      communication: '#FEF0E8',
      interface: '#F0E8F8',
    },
  },
  fonts: {
    default: 'Arial, sans-serif',
    fixed: 'Consolas, Courier New, monospace',
    title: 'Arial Bold',
    symbol: 'Arial',
  },
  sizes: {
    grid: 10,
    pinLength: 20,
    pinSpacing: 50,
    textHeight: 16,
    textHeightSmall: 12,
    titleBlock: {
      height: 100,
      width: 380,
    },
  },
  paper: {
    A4: { width: 841, height: 595 },
    A3: { width: 1190, height: 841 },
  },
};

export interface JLCSymbol {
  id: string;
  name: string;
  type: 'IC' | 'Resistor' | 'Capacitor' | 'Inductor' | 'Diode' | 'LED' | 'Connector' | 'Crystal' | 'Switch' | 'Button' | 'Fuse' | 'VoltageRegulator' | 'Transistor';
  refDes: string;
  pinCount: number;
  pins: JLCPin[];
  width: number;
  height: number;
  bodyWidth?: number;
  bodyHeight?: number;
  footprint?: string;
  datasheet?: string;
}

export interface JLCPin {
  number: string;
  name: string;
  type: 'input' | 'output' | 'bidirectional' | 'power' | 'ground' | 'noconnect';
  side: 'left' | 'right' | 'top' | 'bottom';
  position: number;
  electricalType?: 'IO' | 'PWR' | 'GND' | 'NC' | 'PASSIVE';
}

export const JLC_SYMBOLS: JLCSymbol[] = [
  {
    id: 'resistor_0805',
    name: 'R',
    type: 'Resistor',
    refDes: 'R',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0, electricalType: 'PASSIVE' },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0, electricalType: 'PASSIVE' },
    ],
    width: 100,
    height: 30,
    bodyWidth: 60,
    bodyHeight: 25,
    footprint: '0805',
  },
  {
    id: 'resistor_1206',
    name: 'R',
    type: 'Resistor',
    refDes: 'R',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0, electricalType: 'PASSIVE' },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0, electricalType: 'PASSIVE' },
    ],
    width: 120,
    height: 35,
    bodyWidth: 80,
    bodyHeight: 30,
    footprint: '1206',
  },
  {
    id: 'capacitor_0805_ceramic',
    name: 'C',
    type: 'Capacitor',
    refDes: 'C',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0, electricalType: 'PASSIVE' },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0, electricalType: 'PASSIVE' },
    ],
    width: 100,
    height: 40,
    bodyWidth: 40,
    bodyHeight: 30,
    footprint: '0805',
  },
  {
    id: 'capacitor_0805_electrolytic',
    name: 'C',
    type: 'Capacitor',
    refDes: 'C',
    pinCount: 2,
    pins: [
      { number: '1', name: '+', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '-', type: 'bidirectional', side: 'right', position: 0 },
    ],
    width: 100,
    height: 50,
    bodyWidth: 50,
    bodyHeight: 40,
    footprint: '0805',
  },
  {
    id: 'inductor_0603',
    name: 'L',
    type: 'Inductor',
    refDes: 'L',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0, electricalType: 'PASSIVE' },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0, electricalType: 'PASSIVE' },
    ],
    width: 100,
    height: 40,
    bodyWidth: 60,
    bodyHeight: 30,
    footprint: '0603',
  },
  {
    id: 'led_0805',
    name: 'LED',
    type: 'LED',
    refDes: 'D',
    pinCount: 2,
    pins: [
      { number: '1', name: 'A', type: 'output', side: 'left', position: 0 },
      { number: '2', name: 'K', type: 'input', side: 'right', position: 0 },
    ],
    width: 100,
    height: 40,
    bodyWidth: 60,
    bodyHeight: 30,
    footprint: '0805',
  },
  {
    id: 'diode_1n4148',
    name: 'D',
    type: 'Diode',
    refDes: 'D',
    pinCount: 2,
    pins: [
      { number: '1', name: 'A', type: 'input', side: 'left', position: 0 },
      { number: '2', name: 'K', type: 'output', side: 'right', position: 0 },
    ],
    width: 100,
    height: 40,
    bodyWidth: 60,
    bodyHeight: 30,
    footprint: 'DO-35',
  },
  {
    id: 'crystal_hc49s',
    name: 'Y',
    type: 'Crystal',
    refDes: 'Y',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0 },
    ],
    width: 120,
    height: 50,
    bodyWidth: 80,
    bodyHeight: 35,
    footprint: 'HC-49S',
  },
  {
    id: 'crystal_smd',
    name: 'Y',
    type: 'Crystal',
    refDes: 'Y',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '2', type: 'bidirectional', side: 'right', position: 0 },
    ],
    width: 100,
    height: 40,
    bodyWidth: 60,
    bodyHeight: 28,
    footprint: '3225',
  },
  {
    id: 'header_ph_2p',
    name: 'CONN',
    type: 'Connector',
    refDes: 'J',
    pinCount: 2,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '2', type: 'bidirectional', side: 'left', position: 1 },
    ],
    width: 60,
    height: 70,
    footprint: 'PH-2P',
  },
  {
    id: 'header_ph_4',
    name: 'CONN',
    type: 'Connector',
    refDes: 'J',
    pinCount: 4,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '2', type: 'bidirectional', side: 'left', position: 1 },
      { number: '3', name: '3', type: 'bidirectional', side: 'left', position: 2 },
      { number: '4', name: '4', type: 'bidirectional', side: 'left', position: 3 },
    ],
    width: 60,
    height: 130,
    footprint: 'PH-4',
  },
  {
    id: 'header_ph_6',
    name: 'CONN',
    type: 'Connector',
    refDes: 'J',
    pinCount: 6,
    pins: [
      { number: '1', name: '1', type: 'bidirectional', side: 'left', position: 0 },
      { number: '2', name: '2', type: 'bidirectional', side: 'left', position: 1 },
      { number: '3', name: '3', type: 'bidirectional', side: 'left', position: 2 },
      { number: '4', name: '4', type: 'bidirectional', side: 'left', position: 3 },
      { number: '5', name: '5', type: 'bidirectional', side: 'left', position: 4 },
      { number: '6', name: '6', type: 'bidirectional', side: 'left', position: 5 },
    ],
    width: 60,
    height: 210,
    footprint: 'PH-6',
  },
  {
    id: 'swd_4pin',
    name: 'SWD',
    type: 'Connector',
    refDes: 'J',
    pinCount: 4,
    pins: [
      { number: '1', name: 'VCC', type: 'power', side: 'left', position: 0 },
      { number: '2', name: 'SWDIO', type: 'bidirectional', side: 'left', position: 1 },
      { number: '3', name: 'SWCLK', type: 'input', side: 'left', position: 2 },
      { number: '4', name: 'GND', type: 'ground', side: 'left', position: 3 },
    ],
    width: 60,
    height: 130,
    footprint: 'HDR-4',
  },
  {
    id: 'uart_4pin',
    name: 'UART',
    type: 'Connector',
    refDes: 'J',
    pinCount: 4,
    pins: [
      { number: '1', name: 'GND', type: 'ground', side: 'left', position: 0 },
      { number: '2', name: 'TX', type: 'output', side: 'left', position: 1 },
      { number: '3', name: 'RX', type: 'input', side: 'left', position: 2 },
      { number: '4', name: 'VCC', type: 'power', side: 'left', position: 3 },
    ],
    width: 60,
    height: 130,
    footprint: 'PH-4',
  },
  {
    id: 'ams1117_33',
    name: 'AMS1117-3.3',
    type: 'VoltageRegulator',
    refDes: 'U',
    pinCount: 3,
    pins: [
      { number: '1', name: 'GND', type: 'ground', side: 'left', position: 0 },
      { number: '2', name: 'VOUT', type: 'output', side: 'right', position: 0 },
      { number: '3', name: 'VIN', type: 'input', side: 'left', position: 1 },
    ],
    width: 120,
    height: 80,
    bodyWidth: 80,
    bodyHeight: 55,
    footprint: 'SOT-223',
  },
  {
    id: 'lm1117_33',
    name: 'LM1117-3.3',
    type: 'VoltageRegulator',
    refDes: 'U',
    pinCount: 3,
    pins: [
      { number: '1', name: 'GND', type: 'ground', side: 'left', position: 0 },
      { number: '2', name: 'VOUT', type: 'output', side: 'right', position: 0 },
      { number: '3', name: 'VIN', type: 'input', side: 'left', position: 1 },
    ],
    width: 120,
    height: 80,
    bodyWidth: 80,
    bodyHeight: 55,
    footprint: 'SOT-223',
  },
  {
    id: 'stm32f103c8t6',
    name: 'STM32F103C8T6',
    type: 'IC',
    refDes: 'U',
    pinCount: 48,
    pins: [
      { number: '1', name: 'VBAT', type: 'power', side: 'left', position: 0 },
      { number: '2', name: 'PC13', type: 'bidirectional', side: 'left', position: 1 },
      { number: '3', name: 'PC14', type: 'bidirectional', side: 'left', position: 2 },
      { number: '4', name: 'PC15', type: 'bidirectional', side: 'left', position: 3 },
      { number: '5', name: 'PH0-OSC_IN', type: 'input', side: 'left', position: 4 },
      { number: '6', name: 'PH1-OSC_OUT', type: 'output', side: 'left', position: 5 },
      { number: '7', name: 'NRST', type: 'input', side: 'left', position: 6 },
      { number: '8', name: 'VSSA', type: 'ground', side: 'left', position: 7 },
      { number: '9', name: 'VDDA', type: 'power', side: 'left', position: 8 },
      { number: '10', name: 'PA0', type: 'bidirectional', side: 'left', position: 9 },
      { number: '11', name: 'PA1', type: 'bidirectional', side: 'left', position: 10 },
      { number: '12', name: 'PA2', type: 'bidirectional', side: 'left', position: 11 },
      { number: '13', name: 'PA3', type: 'bidirectional', side: 'left', position: 12 },
      { number: '14', name: 'PA4', type: 'bidirectional', side: 'left', position: 13 },
      { number: '15', name: 'PA5', type: 'bidirectional', side: 'left', position: 14 },
      { number: '16', name: 'PA6', type: 'bidirectional', side: 'left', position: 15 },
      { number: '17', name: 'PA7', type: 'bidirectional', side: 'left', position: 16 },
      { number: '18', name: 'PB0', type: 'bidirectional', side: 'right', position: 0 },
      { number: '19', name: 'PB1', type: 'bidirectional', side: 'right', position: 1 },
      { number: '20', name: 'PB2', type: 'bidirectional', side: 'right', position: 2 },
      { number: '21', name: 'PB10', type: 'bidirectional', side: 'right', position: 3 },
      { number: '22', name: 'PB11', type: 'bidirectional', side: 'right', position: 4 },
      { number: '23', name: 'PB12', type: 'bidirectional', side: 'right', position: 5 },
      { number: '24', name: 'PB13', type: 'bidirectional', side: 'right', position: 6 },
      { number: '25', name: 'PB14', type: 'bidirectional', side: 'right', position: 7 },
      { number: '26', name: 'PB15', type: 'bidirectional', side: 'right', position: 8 },
      { number: '27', name: 'PA8', type: 'bidirectional', side: 'right', position: 9 },
      { number: '28', name: 'PA9-USART1_TX', type: 'bidirectional', side: 'right', position: 10 },
      { number: '29', name: 'PA10-USART1_RX', type: 'bidirectional', side: 'right', position: 11 },
      { number: '30', name: 'PA11', type: 'bidirectional', side: 'right', position: 12 },
      { number: '31', name: 'PA12', type: 'bidirectional', side: 'right', position: 13 },
      { number: '32', name: 'PA15', type: 'bidirectional', side: 'right', position: 14 },
      { number: '33', name: 'PB3', type: 'bidirectional', side: 'right', position: 15 },
      { number: '34', name: 'PB4', type: 'bidirectional', side: 'right', position: 16 },
      { number: '35', name: 'PB5', type: 'bidirectional', side: 'right', position: 17 },
      { number: '36', name: 'PB6-I2C1_SCL', type: 'bidirectional', side: 'right', position: 18 },
      { number: '37', name: 'PB7-I2C1_SDA', type: 'bidirectional', side: 'right', position: 19 },
      { number: '38', name: 'BOOT0', type: 'input', side: 'right', position: 20 },
      { number: '39', name: 'VSS', type: 'ground', side: 'right', position: 21 },
      { number: '40', name: 'VDD', type: 'power', side: 'right', position: 22 },
    ],
    width: 200,
    height: 420,
    bodyWidth: 160,
    bodyHeight: 380,
    footprint: 'LQFP-48',
  },
  {
    id: 'esp32_wroom',
    name: 'ESP32-WROOM',
    type: 'IC',
    refDes: 'U',
    pinCount: 38,
    pins: [
      { number: '1', name: 'GND', type: 'ground', side: 'left', position: 0 },
      { number: '2', name: '3V3', type: 'power', side: 'left', position: 1 },
      { number: '3', name: 'EN', type: 'input', side: 'left', position: 2 },
      { number: '4', name: 'TXD0', type: 'output', side: 'left', position: 3 },
      { number: '5', name: 'RXD0', type: 'input', side: 'left', position: 4 },
      { number: '6', name: 'IO21', type: 'bidirectional', side: 'left', position: 5 },
      { number: '7', name: 'IO22', type: 'bidirectional', side: 'left', position: 6 },
      { number: '8', name: 'IO19', type: 'bidirectional', side: 'left', position: 7 },
      { number: '9', name: 'IO18', type: 'bidirectional', side: 'left', position: 8 },
      { number: '10', name: 'IO5', type: 'bidirectional', side: 'left', position: 9 },
      { number: '11', name: 'IO17', type: 'bidirectional', side: 'left', position: 10 },
      { number: '12', name: 'IO16', type: 'bidirectional', side: 'left', position: 11 },
      { number: '13', name: 'IO4', type: 'bidirectional', side: 'left', position: 12 },
      { number: '14', name: 'IO0', type: 'bidirectional', side: 'left', position: 13 },
      { number: '15', name: 'IO2', type: 'bidirectional', side: 'left', position: 14 },
      { number: '16', name: 'IO15', type: 'bidirectional', side: 'left', position: 15 },
      { number: '17', name: 'IO1', type: 'bidirectional', side: 'left', position: 16 },
      { number: '18', name: 'IO3', type: 'bidirectional', side: 'left', position: 17 },
      { number: '19', name: 'NC', type: 'noconnect', side: 'right', position: 0 },
      { number: '20', name: 'NC', type: 'noconnect', side: 'right', position: 1 },
      { number: '21', name: 'NC', type: 'noconnect', side: 'right', position: 2 },
      { number: '22', name: 'IO35', type: 'bidirectional', side: 'right', position: 3 },
      { number: '23', name: 'IO34', type: 'bidirectional', side: 'right', position: 4 },
      { number: '24', name: 'IO38', type: 'bidirectional', side: 'right', position: 5 },
      { number: '25', name: 'IO37', type: 'bidirectional', side: 'right', position: 6 },
      { number: '26', name: 'IO36', type: 'bidirectional', side: 'right', position: 7 },
      { number: '27', name: 'IO39', type: 'bidirectional', side: 'right', position: 8 },
      { number: '28', name: 'IO14', type: 'bidirectional', side: 'right', position: 9 },
      { number: '29', name: 'IO12', type: 'bidirectional', side: 'right', position: 10 },
      { number: '30', name: 'IO13', type: 'bidirectional', side: 'right', position: 11 },
      { number: '31', name: 'IO9', type: 'bidirectional', side: 'right', position: 12 },
      { number: '32', name: 'IO10', type: 'bidirectional', side: 'right', position: 13 },
      { number: '33', name: 'IO11', type: 'bidirectional', side: 'right', position: 14 },
      { number: '34', name: 'IO7', type: 'bidirectional', side: 'right', position: 15 },
      { number: '35', name: 'IO8', type: 'bidirectional', side: 'right', position: 16 },
      { number: '36', name: 'IO6', type: 'bidirectional', side: 'right', position: 17 },
      { number: '37', name: 'GND', type: 'ground', side: 'right', position: 18 },
      { number: '38', name: 'GND', type: 'ground', side: 'right', position: 19 },
    ],
    width: 220,
    height: 380,
    bodyWidth: 180,
    bodyHeight: 340,
    footprint: 'Module',
  },
  {
    id: 'nmosfet',
    name: 'Q',
    type: 'Transistor',
    refDes: 'Q',
    pinCount: 3,
    pins: [
      { number: '1', name: 'G', type: 'input', side: 'left', position: 0 },
      { number: '2', name: 'D', type: 'bidirectional', side: 'left', position: 1 },
      { number: '3', name: 'S', type: 'bidirectional', side: 'left', position: 2 },
    ],
    width: 100,
    height: 70,
    bodyWidth: 60,
    bodyHeight: 45,
    footprint: 'SOT-23',
  },
];

export function getSymbolByFootprint(footprint: string): JLCSymbol | undefined {
  return JLC_SYMBOLS.find(s => s.footprint === footprint);
}

export function getSymbolByType(type: JLCSymbol['type']): JLCSymbol | undefined {
  return JLC_SYMBOLS.find(s => s.type === type);
}

export function getSymbolById(id: string): JLCSymbol | undefined {
  return JLC_SYMBOLS.find(s => s.id === id);
}

export function getAllSymbols(): JLCSymbol[] {
  return JLC_SYMBOLS;
}
