export interface PDFOptions {
  filename?: string;
  title?: string;
  orientation?: 'portrait' | 'landscape';
  format?: 'a4' | 'a3' | 'letter';
  margin?: {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
  };
  quality?: number;
  scale?: number;
}

export interface ExportResult {
  success: boolean;
  filename?: string;
  error?: string;
}

const DEFAULT_OPTIONS: PDFOptions = {
  filename: `export_${Date.now()}.pdf`,
  title: 'Exported Document',
  orientation: 'portrait',
  format: 'a4',
  margin: {
    top: 10,
    right: 10,
    bottom: 10,
    left: 10,
  },
  quality: 2,
  scale: 2,
};

async function loadHtml2Canvas(): Promise<typeof import('html2canvas').default> {
  try {
    const module = await import('html2canvas');
    return module.default;
  } catch {
    throw new Error(
      'html2canvas 库未安装。请运行: npm install html2canvas'
    );
  }
}

async function loadJsPDF(): Promise<typeof import('jspdf').jsPDF> {
  try {
    const module = await import('jspdf');
    return module.jsPDF;
  } catch {
    throw new Error(
      'jspdf 库未安装。请运行: npm install jspdf'
    );
  }
}

export async function exportToPDF(
  element: HTMLElement,
  options: PDFOptions = {}
): Promise<ExportResult> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const margin = { ...DEFAULT_OPTIONS.margin, ...options.margin };

  try {
    const html2canvas = await loadHtml2Canvas();
    const jsPDF = await loadJsPDF();

    const canvas = await html2canvas(element, {
      scale: opts.scale ?? 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png', opts.quality);

    const formatDimensions: Record<string, [number, number]> = {
      a4: [210, 297],
      a3: [297, 420],
      letter: [215.9, 279.4],
    };

    const [baseWidth, baseHeight] = formatDimensions[opts.format ?? 'a4'];
    const pageWidth = opts.orientation === 'landscape' ? baseHeight : baseWidth;
    const pageHeight = opts.orientation === 'landscape' ? baseWidth : baseHeight;

    const marginMm = {
      top: margin.top ?? 10,
      right: margin.right ?? 10,
      bottom: margin.bottom ?? 10,
      left: margin.left ?? 10,
    };

    const contentWidth = pageWidth - marginMm.left - marginMm.right;
    const contentHeight = pageHeight - marginMm.top - marginMm.bottom;

    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(contentWidth / imgWidth, contentHeight / imgHeight);
    const scaledWidth = imgWidth * ratio;
    const scaledHeight = imgHeight * ratio;

    const pdf = new jsPDF({
      orientation: opts.orientation,
      unit: 'mm',
      format: opts.format,
    });

    pdf.setProperties({
      title: opts.title ?? 'Exported Document',
      subject: 'Generated by Embedded Schematic Generator',
      creator: 'Embedded Schematic Generator',
    });

    const totalPages = Math.ceil(scaledHeight / contentHeight);

    for (let page = 0; page < totalPages; page++) {
      if (page > 0) {
        pdf.addPage();
      }

      const sourceY = (page * contentHeight) / ratio;
      const sourceHeight = Math.min(
        contentHeight / ratio,
        imgHeight - sourceY
      );

      if (sourceHeight > 0) {
        const tempCanvas = document.createElement('canvas');
        tempCanvas.width = imgWidth;
        tempCanvas.height = sourceHeight;
        const ctx = tempCanvas.getContext('2d');

        if (ctx) {
          ctx.drawImage(
            canvas,
            0,
            sourceY,
            imgWidth,
            sourceHeight,
            0,
            0,
            imgWidth,
            sourceHeight
          );

          const pageImgData = tempCanvas.toDataURL('image/png', opts.quality);
          const pageScaledHeight = sourceHeight * ratio;

          pdf.addImage(
            pageImgData,
            'PNG',
            marginMm.left,
            marginMm.top,
            scaledWidth,
            pageScaledHeight
          );
        }
      }
    }

    const filename = opts.filename?.endsWith('.pdf')
      ? opts.filename
      : `${opts.filename}.pdf`;

    pdf.save(filename);

    return {
      success: true,
      filename,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : '导出PDF失败',
    };
  }
}

export async function exportElementToPDF(
  elementId: string,
  options: PDFOptions = {}
): Promise<ExportResult> {
  const element = document.getElementById(elementId);
  if (!element) {
    return {
      success: false,
      error: `找不到ID为 "${elementId}" 的元素`,
    };
  }
  return exportToPDF(element, options);
}

export async function exportMultipleElementsToPDF(
  elements: HTMLElement[],
  options: PDFOptions = {}
): Promise<ExportResult> {
  if (elements.length === 0) {
    return {
      success: false,
      error: '没有要导出的元素',
    };
  }

  const container = document.createElement('div');
  container.style.cssText = `
    position: absolute;
    left: -9999px;
    top: 0;
    background: white;
    padding: 20px;
  `;

  elements.forEach((element, index) => {
    const clone = element.cloneNode(true) as HTMLElement;
    if (index > 0) {
      const divider = document.createElement('div');
      divider.style.cssText = 'height: 20px; page-break-before: always;';
      container.appendChild(divider);
    }
    container.appendChild(clone);
  });

  document.body.appendChild(container);

  try {
    const result = await exportToPDF(container, options);
    return result;
  } finally {
    document.body.removeChild(container);
  }
}

export function checkPDFDependencies(): {
  html2canvas: boolean;
  jspdf: boolean;
  allInstalled: boolean;
} {
  let html2canvasInstalled = false;
  let jspdfInstalled = false;

  try {
    require.resolve('html2canvas');
    html2canvasInstalled = true;
  } catch {
    // not installed
  }

  try {
    require.resolve('jspdf');
    jspdfInstalled = true;
  } catch {
    // not installed
  }

  return {
    html2canvas: html2canvasInstalled,
    jspdf: jspdfInstalled,
    allInstalled: html2canvasInstalled && jspdfInstalled,
  };
}

export function getPDFInstallInstructions(): string {
  return `
要使用PDF导出功能，请安装以下依赖:

npm install html2canvas jspdf

或者使用 yarn:

yarn add html2canvas jspdf
  `.trim();
}
